from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .model import ActionValueNet


def _format_cpp_array(values: Iterable[float], indent: str = "    ") -> str:
    rendered = [f"{float(value):.8f}" for value in values]
    lines: list[str] = []
    chunk_size = 6
    for i in range(0, len(rendered), chunk_size):
        chunk = ", ".join(rendered[i : i + chunk_size])
        lines.append(f"{indent}{chunk},")
    if not lines:
        lines.append(f"{indent}")
    return "\n".join(lines)


def _cpp_identifier(text: str) -> str:
    identifier = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in text)
    identifier = identifier.strip("_")
    if not identifier:
        raise ValueError("C++ identifier cannot be empty")
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    return identifier


def _header_guard(output_path: Path) -> str:
    return f"LGEN_BOTS_GENERATED_{_cpp_identifier(output_path.name).upper()}"


def export_cpp_header(
    model: ActionValueNet,
    output_path: Path,
    *,
    namespace_name: str = "xrz_rl_model",
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    state = {name: tensor.detach().cpu().flatten().tolist() for name, tensor in model.state_dict().items()}
    input_dim, hidden1_size, hidden2_size = model.architecture()
    namespace_identifier = _cpp_identifier(namespace_name)
    guard = _header_guard(output_path)

    header = f"""/**
 * @file {output_path.name}
 *
 * Auto-generated by rl/train_xrz_dqn.py.
 * Re-run the trainer to refresh these parameters.
 */

#ifndef {guard}
#define {guard}

#include <array>
#include <cstddef>

namespace {namespace_identifier} {{

inline constexpr std::size_t kInputSize = {input_dim};
inline constexpr std::size_t kHidden1Size = {hidden1_size};
inline constexpr std::size_t kHidden2Size = {hidden2_size};

inline constexpr std::array<double, kInputSize * kHidden1Size> kLayer1Weights = {{
{_format_cpp_array(state['backbone.0.weight'])}
}};

inline constexpr std::array<double, kHidden1Size> kLayer1Bias = {{
{_format_cpp_array(state['backbone.0.bias'])}
}};

inline constexpr std::array<double, kHidden1Size * kHidden2Size> kLayer2Weights = {{
{_format_cpp_array(state['backbone.2.weight'])}
}};

inline constexpr std::array<double, kHidden2Size> kLayer2Bias = {{
{_format_cpp_array(state['backbone.2.bias'])}
}};

inline constexpr std::array<double, kHidden2Size> kOutputWeights = {{
{_format_cpp_array(state['q_head.weight'])}
}};

inline constexpr std::array<double, 1> kOutputBias = {{
{_format_cpp_array(state['q_head.bias'])}
}};

}}  // namespace {namespace_identifier}

#endif  // {guard}
"""

    output_path.write_text(header)
